support fleet configuration
corelight/terraform-aws-sensor pull request #9
Opened 2024-10-18 18:21 UTC by retr0h

# Description

Ability to pair the sensor to Fleet.

Fixes #CLOUD-270, but depends on https://github.com/corelight/terraform-config-sensor/pull/10

## Type of change

Please delete options that are not relevant.

- [ ] Bug Fix
- [x] New Feature
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested locally

2024-10-18 21:01 UTC, thathaneydude approved these changes
Nice work! 😎

2024-10-18 21:03 UTC, thathaneydude requested changes
Need to remove the sensor_config pin to v0.2.0

2024-10-21 17:19 UTC, retr0h commented
> Need to remove the sensor_config pin to v0.2.0

done

2024-10-21 17:21 UTC, thathaneydude approved these changes
👍

2024-10-21 17:27 UTC, merged